version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    target-branch: default
    groups:
      actions-minor:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: 'ixray-team/setup-ixray-compressor*'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    target-branch: default
    groups:
      npm-development:
        dependency-type: development
        update-types:
          - minor
          - patch
      npm-production:
        dependency-type: production
        update-types:
          - patch
