name: 'Run action'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'dist/**'
      - 'package*.json'
      - 'action.json'

jobs:
  setup-latest:
    name: 'Setup latest'

    strategy:
      matrix:
        system:
          - windows-latest

    runs-on: ${{ matrix.system }}

    steps:
      - name: Setup compressor
        id: setup-compressor
        uses: ixray-team/setup-ixray-compressor@d9ad189f877a88e4f63d5baa1ff00a40165be06d
        with:
          codebase: '1.6-stcop'
          release: 'latest'

      - name: Print info
        run: |
          xrCompress
